language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt --upgrade-strategy=eager
  - pip install codecov
# command to run tests
script:
  - cd src/test; pytest
  - pytest --cov=./ --verbose
